### ISSUE TITLE
Switch to GMLPlayer for 000book tag playback

### ISSUE THREAD

**Issue by tbx** [jamiew/blackbook#12]
Yeah! What pieces are missing to do this?

vanderlin player: 
- does fullscreen (only possible with flash)
- doesn't seperate "strokes"
- is flash
- not beeing developed further atm

canvas player:
- is HTML5 JS/Canvas/processing.js
- is beeing actively developed (e.g. as a fork in http://github.com/tbx/webmarker/blob/master/content/wm_canvasplayer.js )

**Comment by jamiew** [comment]
for sure! is there time-accurate playback in it yet? that's the clutch thing Todd nailed

**Comment by tbx** [comment]
true - that is so.good. I have no idea though how hard that'll be to include.

In the wm_canvasplayer.js fork Flo and I are also thinking about re-creating the "recorder" based on canvasplayer. (=webmarker) Also the drippings using the browser's orientation api (my favourite). Flo did ask the question why we are actually using processing.js and NOT just canvas 2D for CP. legit question ,but I think the answer is that processing.js has alot potential.... Ha! We also need someone to implement gml into a web GL 3D-player!!!

**Comment by jamiew** [comment]
Hijacking this ticket to switch from canvasplayer to scott's GMLPlayer, which is wayyyyyyy better:

http://www.graffitimarkuplanguage.com/gml-html5-player/

https://github.com/ScottDowne/GMLpopcorn
